-- PROCEDURE: public.cria_tabelas()

-- DROP PROCEDURE IF EXISTS public.cria_tabelas();

CREATE OR REPLACE PROCEDURE public.cria_tabelas(
	)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	CREATE TABLE ECOSSISTEMAS_INOVACAO(ID SERIAL PRIMARY KEY
									  ,NOME VARCHAR UNIQUE NOT NULL);
									  
	CREATE TABLE CIDADES(ID SERIAL NOT NULL PRIMARY KEY
						,NOME VARCHAR UNIQUE NOT NULL
						,ECO_ID INT NOT NULL
						,FOREIGN KEY (ECO_ID) REFERENCES ECOSSISTEMAS_INOVACAO(ID));
									  
	CREATE TABLE INSTITUICOES(ID SERIAL NOT NULL PRIMARY KEY 
							 ,SIGLA VARCHAR NOT NULL
							 ,NOME VARCHAR NOT NULL
							 ,TIP_INST INT NOT NULL
							 ,NUM_MATRICULAS INT
							 ,SITE VARCHAR
							 ,CID_ID INT NOT NULL
							 ,UNIQUE (NOME, CID_ID)
							 ,FOREIGN KEY (CID_ID) REFERENCES CIDADES(ID));
	COMMENT ON COLUMN INSTITUICOES.TIP_INST IS 'Indica tipo da instiuição. 1 - Ensino, 2 - Pesquisa.';
		  
	CREATE TABLE AMBIENTES_INOV(ID SERIAL NOT NULL PRIMARY KEY 
							   ,SIGLA VARCHAR NOT NULL
							   ,NOME VARCHAR NOT NULL
							   ,TIP_AMB INT NOT NULL
							   ,SITE VARCHAR
							   ,CID_ID INT NOT NULL
							   ,UNIQUE (SIGLA, CID_ID)
							   ,FOREIGN KEY (CID_ID) REFERENCES CIDADES(ID));
	COMMENT ON COLUMN AMBIENTES_INOV.TIP_AMB IS 'Indica tipo do Ambiente de inovação. 
								1 - Aceleradora, 2 - Incubadora, 3 - Parque tecnológico.';
								  
END;
$BODY$;
ALTER PROCEDURE public.cria_tabelas()
    OWNER TO postgres;
