-- PROCEDURE: public.cria_tabelas()

-- DROP PROCEDURE IF EXISTS public.cria_tabelas();

CREATE OR REPLACE PROCEDURE public.cria_tabelas(
	)
LANGUAGE 'plpgsql'
AS $BODY$
BEGIN
	CREATE TABLE ECOSSISTEMAS_INOVACAO(ID SERIAL PRIMARY KEY
									  ,NOME VARCHAR UNIQUE NOT NULL
									  ,PAIS VARCHAR NOT NULL
									  ,ESTADO VARCHAR);
									  
	CREATE TABLE CIDADES(ID SERIAL NOT NULL PRIMARY KEY
						,NOME VARCHAR UNIQUE NOT NULL
						,ECO_ID INT NOT NULL
						,VLR_INVEST NUMERIC(14,2)
						,FOREIGN KEY (ECO_ID) REFERENCES ECOSSISTEMAS_INOVACAO(ID));
									  
	CREATE TABLE INSTITUICOES(ID SERIAL NOT NULL PRIMARY KEY 
							 ,SIGLA VARCHAR NOT NULL
							 ,NOME VARCHAR NOT NULL
							 ,TIP_INST INT NOT NULL
							 ,IND_PRINCIPAL INT NOT NULL
							 ,NUM_MATRICULAS INT
							 ,NUM_BOLSAS INT
							 ,SITE VARCHAR
							 ,CID_ID INT NOT NULL
							 ,UNIQUE (NOME, CID_ID)
							 ,FOREIGN KEY (CID_ID) REFERENCES CIDADES(ID));
	COMMENT ON COLUMN INSTITUICOES.TIP_INST IS 'Indica tipo da instiuição. 1 - Ensino, 2 - Pesquisa.';
	COMMENT ON COLUMN INSTITUICOES.IND_PRINCIPAL IS 'Indica se é o campus principal da instituição. 0 - Não, 1 - Sim';
		  
	CREATE TABLE AMBIENTES_INOV(ID SERIAL NOT NULL PRIMARY KEY 
							   ,SIGLA VARCHAR NOT NULL
							   ,NOME VARCHAR
							   ,TIP_AMB INT NOT NULL
							   ,SITE VARCHAR
							   ,CID_ID INT NOT NULL
							   ,UNIQUE (SIGLA, CID_ID)
							   ,FOREIGN KEY (CID_ID) REFERENCES CIDADES(ID));
	COMMENT ON COLUMN AMBIENTES_INOV.TIP_AMB IS 'Indica tipo do Ambiente de inovação. 
								1 - Aceleradora, 2 - Incubadora, 3 - Parque tecnológico, 4 - Outros.';
		  
	CREATE TABLE STARTUPS(ID SERIAL NOT NULL PRIMARY KEY 
						 ,NOME VARCHAR NOT NULL
						 ,AREA VARCHAR
						 ,SITE VARCHAR
						 ,CID_ID INT NOT NULL
						 ,AMB_ID INT
						 ,UNIQUE (NOME)
						 ,FOREIGN KEY (CID_ID) REFERENCES CIDADES(ID)
						 ,FOREIGN KEY (AMB_ID) REFERENCES AMBIENTES_INOV(ID));
									  
	CREATE TABLE PESSOAS(ID SERIAL NOT NULL PRIMARY KEY
						,NOME VARCHAR NOT NULL
						,IND_PESQ INT
						,TIP_TITULO INT
						,ECO_ID INT NOT NULL
					    ,FOREIGN KEY (ECO_ID) REFERENCES ECOSSISTEMAS_INOVACAO(ID));
	COMMENT ON COLUMN PESSOAS.IND_PESQ IS 'Indica se é pesquisador. 0 - Não, 1 - Sim.';
	COMMENT ON COLUMN PESSOAS.TIP_TITULO IS 'Indica o título. 
								1 - Especialização, 2 - Mestrado, 3 - Doutorado, 4 - Outro/Não Informado.';
		  
	CREATE TABLE PRODUCOES(ID SERIAL NOT NULL PRIMARY KEY 
						  ,NOME VARCHAR NOT NULL
					      ,TIP_PROD INT NOT NULL
						  ,AUTOR VARCHAR NOT NULL
						  ,INST_ID INT NOT NULL
						  ,UNIQUE (NOME, AUTOR)
						  ,FOREIGN KEY (INST_ID) REFERENCES INSTITUICOES(ID));
	COMMENT ON COLUMN PRODUCOES.TIP_PROD IS 'Indica tipo da Produção. 
								1 - Patente, 2 - Projeto de Pesquisa, 3 - Tese, 4 - Dissertação.';
									  
	CREATE TABLE EMPRESAS_ALTO_CRESC(ID SERIAL NOT NULL PRIMARY KEY
									,NOME VARCHAR NOT NULL
									,AREA VARCHAR
									,RECEITA_24 NUMERIC(14, 2)
									,RECEITA_23 NUMERIC(14, 2)
									,CID_ID INT NOT NULL
									,UNIQUE(NOME, CID_ID)
									,FOREIGN KEY (CID_ID) REFERENCES CIDADES(ID));
									  
	CREATE TABLE ENTIDADES_GOV(ID SERIAL NOT NULL PRIMARY KEY
							  ,ENTIDADE VARCHAR NOT NULL
							  ,NOME_UNI VARCHAR 
							  ,CID_ID INT NOT NULL
							  ,UNIQUE(NOME_UNI, CID_ID)
							  ,FOREIGN KEY (CID_ID) REFERENCES CIDADES(ID));
								  
END;
$BODY$;
ALTER PROCEDURE public.cria_tabelas()
    OWNER TO postgres;
